// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitChat(arg1) {
  return window['go']['main']['App']['CommitChat'](arg1);
}

export function FetchRemote(arg1) {
  return window['go']['main']['App']['FetchRemote'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetRemote(arg1) {
  return window['go']['main']['App']['GetRemote'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function LoadRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadRepo'](arg1, arg2, arg3, arg4);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveRemoteToken(arg1, arg2) {
  return window['go']['main']['App']['SaveRemoteToken'](arg1, arg2);
}

export function SelectRepo() {
  return window['go']['main']['App']['SelectRepo']();
}

export function TestAI() {
  return window['go']['main']['App']['TestAI']();
}
