// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListBranches(arg1:string):Promise<Array<main.BranchInfo>>;

export function LoadRepo(arg1:string,arg2:Array<string>):Promise<main.RepoGraph>;

export function SelectRepo():Promise<string>;
