// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function LoadRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadRepo'](arg1, arg2, arg3, arg4);
}

export function SelectRepo() {
  return window['go']['main']['App']['SelectRepo']();
}
