// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchRemote(arg1:string):Promise<void>;

export function GetRemote(arg1:string):Promise<main.RemoteInfo>;

export function ListBranches(arg1:string):Promise<Array<main.BranchInfo>>;

export function LoadRepo(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<main.RepoGraph>;

export function SaveRemoteToken(arg1:string,arg2:string):Promise<void>;

export function SelectRepo():Promise<string>;
